name: Build mkdocs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build docs
        uses: jnanadarshan/mkdocs-build-action@v0.24
